# Generated by Django 3.1 on 2023-02-08 12:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=255, verbose_name='Наименование жанра')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование книги')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('imageCover', models.ImageField(upload_to='books/covers/', verbose_name='Обложка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации')),
                ('audioFile', models.FileField(upload_to='books/audio/', verbose_name='Файл mp3')),
                ('isRecommended', models.BooleanField(blank=True, default=False, null=True, verbose_name='Включить/отключить рекомендацию')),
                ('isChart', models.BooleanField(blank=True, default=False, null=True, verbose_name='Включить/отключить чарт')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebookApp.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
